# Generated by Django 6.0.6 on 2026-07-15 21:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('ultima_movimentacao_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_estoque', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_estoque', to='empresas.matriz')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_estoque', to='produtos.produto')),
            ],
            options={
                'ordering': ['loja__nome', 'produto__nome'],
                'indexes': [models.Index(fields=['matriz', 'produto'], name='saldo_matriz_produto_idx'), models.Index(fields=['matriz', 'loja', 'quantidade_atual'], name='saldo_loja_quantidade_idx'), models.Index(fields=['loja', 'ultima_movimentacao_em'], name='saldo_loja_ultima_mov_idx')],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'loja', 'produto'), name='uq_saldo_matriz_loja_produto'), models.CheckConstraint(condition=models.Q(('quantidade_atual__gte', 0)), name='saldo_quantidade_nao_negativa')],
            },
        ),
    ]
