# Generated by Django 6.0.6 on 2026-07-15 22:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('saldo_inicial', 'Saldo inicial'), ('entrada_manual', 'Entrada manual'), ('saida_manual', 'Saída manual'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo'), ('transferencia_entrada', 'Transferência - entrada'), ('transferencia_saida', 'Transferência - saída'), ('inventario_entrada', 'Inventário - entrada'), ('inventario_saida', 'Inventário - saída'), ('reversao_entrada', 'Reversão - entrada'), ('reversao_saida', 'Reversão - saída'), ('compra', 'Compra'), ('devolucao_compra', 'Devolução de compra'), ('venda', 'Venda'), ('devolucao_venda', 'Devolução de venda')], db_index=True, max_length=40)),
                ('natureza', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], db_index=True, max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('saldo_anterior', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('saldo_posterior', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('observacao', models.TextField(blank=True)),
                ('documento_referencia', models.CharField(blank=True, db_index=True, max_length=100)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('inventario', 'Inventário'), ('transferencia', 'Transferência'), ('compra', 'Compra'), ('venda', 'Venda'), ('fiscal', 'Fiscal'), ('sistema', 'Sistema')], db_index=True, max_length=30)),
                ('origem_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('chave_idempotencia', models.CharField(blank=True, db_index=True, max_length=150)),
                ('grupo_transferencia', models.UUIDField(blank=True, db_index=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='empresas.matriz')),
                ('movimentacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversoes', to='estoque.movimentacaoestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='produtos.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['matriz', 'loja', 'criado_em'], name='mov_matriz_loja_data_idx'), models.Index(fields=['matriz', 'produto', 'criado_em'], name='mov_matriz_prod_data_idx'), models.Index(fields=['matriz', 'tipo', 'criado_em'], name='mov_matriz_tipo_data_idx'), models.Index(fields=['matriz', 'natureza', 'criado_em'], name='mov_matriz_nat_data_idx'), models.Index(fields=['matriz', 'origem', 'origem_id'], name='mov_matriz_origem_idx'), models.Index(fields=['matriz', 'documento_referencia'], name='mov_matriz_documento_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='mov_quantidade_positiva'), models.CheckConstraint(condition=models.Q(('saldo_anterior__gte', 0)), name='mov_saldo_anterior_nao_neg'), models.CheckConstraint(condition=models.Q(('saldo_posterior__gte', 0)), name='mov_saldo_posterior_nao_neg'), models.UniqueConstraint(condition=models.Q(('chave_idempotencia', ''), _negated=True), fields=('matriz', 'chave_idempotencia'), name='uq_mov_matriz_idempotencia'), models.UniqueConstraint(condition=models.Q(('movimentacao_origem__isnull', False)), fields=('movimentacao_origem',), name='uq_mov_reversao_origem')],
            },
        ),
    ]
