# Generated by Django 6.0.6 on 2026-07-16 23:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('estoque', '0002_movimentacaoestoque'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('confirmada', 'Confirmada'), ('liberada', 'Liberada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], db_index=True, default='ativa', max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('inventario', 'Inventário'), ('transferencia', 'Transferência'), ('compra', 'Compra'), ('venda', 'Venda'), ('fiscal', 'Fiscal'), ('sistema', 'Sistema')], db_index=True, max_length=30)),
                ('origem_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('chave_idempotencia', models.CharField(blank=True, db_index=True, max_length=150)),
                ('documento_referencia', models.CharField(blank=True, db_index=True, max_length=100)),
                ('expira_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('liberada_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('expirada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_estoque', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_estoque', to='empresas.matriz')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_estoque', to='produtos.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['matriz', 'loja', 'status'], name='res_matriz_loja_status_idx'), models.Index(fields=['matriz', 'produto', 'status'], name='res_matriz_prod_status_idx'), models.Index(fields=['matriz', 'expira_em'], name='res_matriz_expira_idx'), models.Index(fields=['matriz', 'origem', 'origem_id'], name='res_matriz_origem_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='res_quantidade_positiva'), models.UniqueConstraint(condition=models.Q(('chave_idempotencia', ''), _negated=True), fields=('matriz', 'chave_idempotencia'), name='uq_res_matriz_idempotencia')],
            },
        ),
    ]
