# Generated by Django 6.0.6 on 2026-06-27 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('criar', 'Criar'), ('editar', 'Editar'), ('excluir', 'Excluir'), ('importar', 'Importar'), ('disparar', 'Disparar'), ('acessar', 'Acessar')], db_index=True, max_length=30)),
                ('recurso', models.CharField(db_index=True, max_length=150)),
                ('recurso_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='empresas.loja')),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='empresas.matriz')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['matriz', 'acao'], name='auditoria_r_matriz__d40a6e_idx'), models.Index(fields=['matriz', 'criado_em'], name='auditoria_r_matriz__9b307e_idx'), models.Index(fields=['usuario', 'criado_em'], name='auditoria_r_usuario_191284_idx'), models.Index(fields=['recurso', 'recurso_id'], name='auditoria_r_recurso_0b9bba_idx')],
            },
        ),
    ]
