# Generated by Django 6.0.6 on 2026-06-22 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_cashback', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('dias_liberacao', models.PositiveIntegerField(default=7)),
                ('dias_expiracao', models.PositiveIntegerField(default=45)),
                ('valor_minimo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('texto_email_saldo', models.TextField(blank=True)),
                ('texto_email_aniversario', models.TextField(blank=True)),
                ('texto_sms_aniversario', models.TextField(blank=True)),
                ('matriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresas.matriz')),
            ],
        ),
    ]
