# Generated by Django 6.0.6 on 2026-06-22 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_cashback', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('dias_liberacao', models.PositiveIntegerField(default=7)),
                ('dias_expiracao', models.PositiveIntegerField(default=45)),
                ('valor_minimo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enviar_email_saldo', models.BooleanField(default=True)),
                ('enviar_email_aniversario', models.BooleanField(default=True)),
                ('enviar_sms_aniversario', models.BooleanField(default=False)),
                ('mensagem_email_saldo', models.TextField(blank=True)),
                ('mensagem_email_aniversario', models.TextField(blank=True)),
                ('mensagem_sms_aniversario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='empresas.matriz')),
            ],
        ),
    ]
