# Generated by Django 6.0.6 on 2026-07-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='percentual_maximo_beneficio',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
    ]
