# Generated by Django 6.0.6 on 2026-07-26 16:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atacado_ativo', models.BooleanField(default=False)),
                ('pedido_minimo_atacado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto_atacado_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cashback_ativo', models.BooleanField(default=True)),
                ('voucher_ativo', models.BooleanField(default=True)),
                ('promocoes_ativas', models.BooleanField(default=True)),
                ('brindes_ativos', models.BooleanField(default=True)),
                ('arredondamento_ativo', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_comercial', to='empresas.matriz')),
            ],
            options={
                'verbose_name': 'configuracao comercial',
                'verbose_name_plural': 'configuracoes comerciais',
                'ordering': ('matriz_id',),
            },
        ),
    ]
