# Generated by Django 6.0.6 on 2026-10-02 22:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComissaoMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exigir_minimo_individual', models.BooleanField(default=False)),
                ('minimo_vendas_vendedor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_comissao', to='empresas.matriz')),
            ],
            options={
                'verbose_name': 'ConfiguraÃ§Ã£o de comissÃ£o da matriz',
                'verbose_name_plural': 'ConfiguraÃ§Ãµes de comissÃ£o das matrizes',
                'constraints': [models.CheckConstraint(condition=models.Q(('minimo_vendas_vendedor__gte', 0)), name='ck_cfg_comissao_minimo_nao_negativo')],
            },
        ),
        migrations.CreateModel(
            name='MetaComissaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('percentual_comissao', models.DecimalField(decimal_places=4, max_digits=7)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_comissao', to='empresas.loja')),
            ],
            options={
                'verbose_name': 'Meta de comissÃ£o da loja',
                'verbose_name_plural': 'Metas de comissÃ£o das lojas',
                'ordering': ['valor_meta', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('loja', 'valor_meta'), name='uq_meta_comissao_loja_valor'), models.CheckConstraint(condition=models.Q(('valor_meta__gte', 0)), name='ck_meta_comissao_valor_nao_negativo'), models.CheckConstraint(condition=models.Q(('percentual_comissao__gte', 0)), name='ck_meta_comissao_percentual_nao_negativo')],
            },
        ),
    ]
