# Generated by Django 6.0.6 on 2026-10-03 00:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracaocomissaomatriz_metacomissaoloja'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_ano', models.PositiveSmallIntegerField()),
                ('competencia_mes', models.PositiveSmallIntegerField()),
                ('total_vendas_loja', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_meta_atingida', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percentual_aplicado', models.DecimalField(decimal_places=4, max_digits=7)),
                ('exigir_minimo_individual', models.BooleanField(default=False)),
                ('minimo_individual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_comissao', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_comissao', to='empresas.matriz')),
            ],
            options={
                'ordering': ['-competencia_ano', '-competencia_mes', 'loja_id'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_uuid_original', models.UUIDField()),
                ('vendedor_nome_original', models.CharField(max_length=300)),
                ('total_vendas_vendedor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('elegivel', models.BooleanField(default=True)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes_historicas', to=settings.AUTH_USER_MODEL)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes_vendedores', to='configuracoes.fechamentocomissao')),
            ],
            options={
                'ordering': ['fechamento_id', 'vendedor_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fechamentocomissao',
            constraint=models.UniqueConstraint(fields=('loja', 'competencia_ano', 'competencia_mes'), name='uq_fech_comissao_loja_comp'),
        ),
        migrations.AddConstraint(
            model_name='fechamentocomissao',
            constraint=models.CheckConstraint(condition=models.Q(('competencia_mes__gte', 1), ('competencia_mes__lte', 12)), name='ck_fech_comissao_mes_1_12'),
        ),
        migrations.AddConstraint(
            model_name='fechamentocomissao',
            constraint=models.CheckConstraint(condition=models.Q(('total_vendas_loja__gte', 0)), name='ck_fech_comissao_total_nao_neg'),
        ),
        migrations.AddConstraint(
            model_name='fechamentocomissao',
            constraint=models.CheckConstraint(condition=models.Q(('percentual_aplicado__gte', 0)), name='ck_fech_comissao_pct_nao_neg'),
        ),
        migrations.AddConstraint(
            model_name='fechamentocomissao',
            constraint=models.CheckConstraint(condition=models.Q(('minimo_individual__gte', 0)), name='ck_fech_comissao_min_nao_neg'),
        ),
        migrations.AddConstraint(
            model_name='comissaovendedor',
            constraint=models.UniqueConstraint(fields=('fechamento', 'vendedor'), name='uq_comissao_fech_vendedor'),
        ),
        migrations.AddConstraint(
            model_name='comissaovendedor',
            constraint=models.CheckConstraint(condition=models.Q(('total_vendas_vendedor__gte', 0)), name='ck_comissao_vend_total_nao_neg'),
        ),
        migrations.AddConstraint(
            model_name='comissaovendedor',
            constraint=models.CheckConstraint(condition=models.Q(('valor_comissao__gte', 0)), name='ck_comissao_vend_valor_nao_neg'),
        ),
    ]
