# Generated by Django 6.0.6 on 2026-07-22 00:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='empresas.matriz', verbose_name='Matriz')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'rh_departamento',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['matriz', 'ativo'], name='idx_rh_depart_matriz_ativo'), models.Index(fields=['nome'], name='idx_rh_depart_nome')],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'nome'), name='uk_rh_departamento_matriz_nome')],
            },
        ),
    ]
