# Generated by Django 6.0.6 on 2026-07-22 11:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('rh', '0002_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, default='', max_length=20, verbose_name='RG')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='rh.cargo', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='rh.departamento', verbose_name='Departamento')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresas.matriz', verbose_name='Matriz')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'rh_funcionario',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['matriz', 'ativo'], name='idx_rh_func_matriz_ativo'), models.Index(fields=['nome_completo'], name='idx_rh_func_nome'), models.Index(fields=['cpf'], name='idx_rh_func_cpf')],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'cpf'), name='uk_rh_funcionario_matriz_cpf')],
            },
        ),
    ]
