# Generated by Django 6.0.6 on 2026-07-12 17:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produtos', to='empresas.matriz')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_produtos', to='empresas.matriz')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_medida_produtos', to='empresas.matriz')),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50)),
                ('codigo_interno', models.CharField(db_index=True, max_length=50)),
                ('gtin', models.CharField(blank=True, db_index=True, help_text='Código de barras GTIN/EAN.', max_length=14)),
                ('ncm', models.CharField(blank=True, db_index=True, help_text='NCM contendo até 8 números.', max_length=8)),
                ('nome', models.CharField(db_index=True, max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('custo_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('origem_preco', models.CharField(choices=[('manual', 'Manual'), ('formacao_preco', 'Formação de preço')], db_index=True, default='manual', max_length=30)),
                ('peso_liquido_gramas', models.PositiveIntegerField(blank=True, help_text='Peso ou conteúdo líquido do produto em gramas.', null=True)),
                ('peso_bruto_gramas', models.PositiveIntegerField(blank=True, help_text='Peso total do produto embalado para cálculo de frete.', null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('largura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comprimento_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('controla_estoque', models.BooleanField(db_index=True, default=True)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('descontinuado', 'Descontinuado')], db_index=True, default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.marca')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='empresas.matriz')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.unidademedida')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['matriz', 'nome'], name='prod_cat_matriz_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['matriz', 'ativa'], name='prod_cat_matriz_ativa_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('matriz', 'nome'), name='uq_categoria_produto_matriz_nome'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['matriz', 'nome'], name='prod_marca_matriz_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['matriz', 'ativa'], name='prod_marca_matriz_ativa_idx'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(fields=('matriz', 'nome'), name='uq_marca_produto_matriz_nome'),
        ),
        migrations.AddIndex(
            model_name='unidademedida',
            index=models.Index(fields=['matriz', 'sigla'], name='prod_unid_matriz_sigla_idx'),
        ),
        migrations.AddIndex(
            model_name='unidademedida',
            index=models.Index(fields=['matriz', 'ativa'], name='prod_unid_matriz_ativa_idx'),
        ),
        migrations.AddConstraint(
            model_name='unidademedida',
            constraint=models.UniqueConstraint(fields=('matriz', 'sigla'), name='uq_unidade_produto_matriz_sigla'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['matriz', 'nome'], name='produto_matriz_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['matriz', 'status'], name='produto_matriz_status_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['matriz', 'categoria'], name='produto_matriz_categoria_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['matriz', 'marca'], name='produto_matriz_marca_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['matriz', 'codigo_interno'], name='produto_matriz_codigo_idx'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('matriz', 'codigo_interno'), name='uq_produto_matriz_codigo_interno'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('matriz', 'sku'), name='uq_produto_matriz_sku_preenchido'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('gtin', ''), _negated=True), fields=('matriz', 'gtin'), name='uq_produto_matriz_gtin_preenchido'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('custo_base__gte', 0)), name='produto_custo_base_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('preco_venda__gte', 0)), name='produto_preco_venda_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('estoque_minimo__gte', 0)), name='produto_estoque_minimo_nao_negativo'),
        ),
    ]
