# Generated by Django 6.0.6 on 2026-08-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0022_seed_regra_fiscal_homologacao'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='beneficio_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_padrao', to='fiscal.beneficiofiscal', verbose_name='Beneficio fiscal padrao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_classificados', to='fiscal.cest', verbose_name='CEST'),
        ),
        migrations.AddField(
            model_name='produto',
            name='csosn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_padrao', to='fiscal.csosn', verbose_name='CSOSN padrao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_cofins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_padrao', to='fiscal.cstcofins', verbose_name='CST COFINS padrao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_icms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_padrao', to='fiscal.csticms', verbose_name='CST ICMS padrao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_ipi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_padrao', to='fiscal.cstipi', verbose_name='CST IPI padrao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_pis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_padrao', to='fiscal.cstpis', verbose_name='CST PIS padrao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_classificados', to='fiscal.ncm', verbose_name='NCM oficial'),
        ),
        migrations.AddField(
            model_name='produto',
            name='origem_mercadoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_classificados', to='fiscal.origemmercadoria', verbose_name='Origem da mercadoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='regra_fiscal_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_padrao', to='fiscal.regrafiscal', verbose_name='Regra fiscal padrao'),
        ),
    ]
