# Generated by Django 6.0.6 on 2026-06-30 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(db_index=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_extras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['permissao'],
                'indexes': [models.Index(fields=['usuario', 'permissao'], name='accounts_pe_usuario_899550_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'permissao'), name='uq_usuario_permissao')],
            },
        ),
    ]
