# Generated by Django 6.0.6 on 2026-06-22 21:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_cashback', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('dias_para_liberar', models.PositiveIntegerField(default=7)),
                ('dias_para_expirar', models.PositiveIntegerField(default=45)),
                ('envio_email_saldo', models.BooleanField(default=True)),
                ('envio_aniversario_email', models.BooleanField(default=True)),
                ('envio_aniversario_sms', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_cashback', to='empresas.loja')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_cashback', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField(default=django.utils.timezone.localdate)),
                ('data_liberacao', models.DateField()),
                ('data_expiracao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('disponivel', 'Disponível'), ('usado', 'Usado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_cashback', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_cashback', to='empresas.loja')),
            ],
            options={
                'ordering': ['-data_compra', '-criado_em'],
            },
        ),
    ]
