# Generated by Django 6.0.6 on 2026-06-22 22:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_cashback', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_cashback', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_utilizado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_compra', models.DateField(default=django.utils.timezone.localdate)),
                ('data_liberacao', models.DateField(db_index=True)),
                ('data_expiracao', models.DateField(db_index=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_cashback', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_cashback', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_cashback', to='empresas.matriz')),
            ],
            options={
                'ordering': ['-data_compra', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UsoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('valor_usado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_uso', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_cashback', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_cashback', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_cashback', to='empresas.matriz')),
            ],
            options={
                'ordering': ['-data_uso'],
            },
        ),
        migrations.CreateModel(
            name='UsoLancamentoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_utilizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilizacoes', to='cashback.lancamentocashback')),
                ('uso_cashback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cashback.usocashback')),
            ],
        ),
        migrations.AddIndex(
            model_name='lancamentocashback',
            index=models.Index(fields=['matriz', 'cliente'], name='cashback_la_matriz__951731_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocashback',
            index=models.Index(fields=['matriz', 'loja'], name='cashback_la_matriz__10106c_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocashback',
            index=models.Index(fields=['matriz', 'data_liberacao'], name='cashback_la_matriz__f368dc_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocashback',
            index=models.Index(fields=['matriz', 'data_expiracao'], name='cashback_la_matriz__c0d433_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocashback',
            index=models.Index(fields=['matriz', 'cliente', 'data_liberacao'], name='cashback_la_matriz__e7f424_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocashback',
            index=models.Index(fields=['matriz', 'cliente', 'data_expiracao'], name='cashback_la_matriz__3d0c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentocashback',
            index=models.Index(fields=['cliente', 'data_compra'], name='cashback_la_cliente_5581fa_idx'),
        ),
        migrations.AddIndex(
            model_name='usocashback',
            index=models.Index(fields=['matriz', 'cliente'], name='cashback_us_matriz__4e8023_idx'),
        ),
        migrations.AddIndex(
            model_name='usocashback',
            index=models.Index(fields=['matriz', 'loja'], name='cashback_us_matriz__bc7bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='usocashback',
            index=models.Index(fields=['cliente', 'data_uso'], name='cashback_us_cliente_047c56_idx'),
        ),
        migrations.AddIndex(
            model_name='usolancamentocashback',
            index=models.Index(fields=['uso_cashback'], name='cashback_us_uso_cas_84252e_idx'),
        ),
        migrations.AddIndex(
            model_name='usolancamentocashback',
            index=models.Index(fields=['lancamento'], name='cashback_us_lancame_8dbf06_idx'),
        ),
        migrations.AddConstraint(
            model_name='usolancamentocashback',
            constraint=models.CheckConstraint(condition=models.Q(('valor_utilizado__gt', 0)), name='valor_utilizado_maior_que_zero'),
        ),
    ]
