# Generated by Django 6.0.6 on 2026-06-22 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentual_cashback', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_cashback', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_compra', models.DateField(default=django.utils.timezone.localdate)),
                ('data_liberacao', models.DateField()),
                ('data_expiracao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('disponivel', 'Disponível'), ('usado', 'Usado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_cashback', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_cashback', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_cashback', to='empresas.matriz')),
            ],
            options={
                'ordering': ['-data_compra', '-criado_em'],
                'indexes': [models.Index(fields=['matriz', 'cliente'], name='cashback_la_matriz__951731_idx'), models.Index(fields=['matriz', 'loja'], name='cashback_la_matriz__10106c_idx'), models.Index(fields=['matriz', 'status'], name='cashback_la_matriz__a6b3dd_idx'), models.Index(fields=['matriz', 'data_liberacao'], name='cashback_la_matriz__f368dc_idx'), models.Index(fields=['matriz', 'data_expiracao'], name='cashback_la_matriz__c0d433_idx'), models.Index(fields=['cliente', 'status'], name='cashback_la_cliente_688d94_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsoCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_usado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_uso', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_cashback', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_cashback', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_cashback', to='empresas.matriz')),
            ],
            options={
                'ordering': ['-data_uso'],
                'indexes': [models.Index(fields=['matriz', 'cliente'], name='cashback_us_matriz__4e8023_idx'), models.Index(fields=['matriz', 'loja'], name='cashback_us_matriz__bc7bcc_idx'), models.Index(fields=['cliente', 'data_uso'], name='cashback_us_cliente_047c56_idx')],
            },
        ),
    ]
