# Generated by Django 6.0.6 on 2026-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_lancamentocashback_valor_base_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocashback',
            name='chave_idempotencia',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
