# Generated by Django 6.0.6 on 2026-07-11 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0004_preencher_chaves_idempotencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentocashback',
            name='chave_idempotencia',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
