# Generated by Django 6.0.6 on 2026-08-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('fiscal', '0020_seed_beneficio_fiscal_homologacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('codigo_interno', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Codigo interno')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('prioridade', models.PositiveIntegerField(db_index=True, default=100, help_text='Menor numero possui maior prioridade.', verbose_name='Prioridade')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('regime_tributario', models.CharField(choices=[('todos', 'Todos'), ('normal', 'Regime normal'), ('simples', 'Simples Nacional'), ('mei', 'MEI')], db_index=True, default='todos', max_length=12, verbose_name='Regime tributario')),
                ('tipo_operacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida'), ('ambos', 'Entrada e saida')], db_index=True, default='ambos', max_length=10, verbose_name='Tipo de operacao')),
                ('finalidade_operacao', models.CharField(choices=[('venda', 'Venda'), ('compra', 'Compra'), ('devolucao', 'Devolucao'), ('remessa', 'Remessa'), ('transferencia', 'Transferencia')], db_index=True, max_length=16, verbose_name='Finalidade da operacao')),
                ('uf_origem', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='UF de origem')),
                ('uf_destino', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='UF de destino')),
                ('contribuinte_icms', models.BooleanField(blank=True, null=True, verbose_name='Contribuinte de ICMS')),
                ('consumidor_final', models.BooleanField(blank=True, null=True, verbose_name='Consumidor final')),
                ('aliquota_icms', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Aliquota de ICMS')),
                ('reducao_base_icms', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Reducao da base de ICMS')),
                ('aliquota_fcp', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Aliquota de FCP')),
                ('aliquota_mva', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Aliquota de MVA')),
                ('aliquota_pis', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Aliquota de PIS')),
                ('aliquota_cofins', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Aliquota de COFINS')),
                ('aliquota_ipi', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Aliquota de IPI')),
                ('diferimento_icms', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Diferimento de ICMS')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio da vigencia')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim da vigencia')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('beneficio_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.beneficiofiscal', verbose_name='Beneficio fiscal')),
                ('cest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.cest', verbose_name='CEST')),
                ('cfop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.cfop', verbose_name='CFOP')),
                ('csosn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.csosn', verbose_name='CSOSN')),
                ('cst_cofins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.cstcofins', verbose_name='CST COFINS')),
                ('cst_icms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.csticms', verbose_name='CST ICMS')),
                ('cst_ipi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.cstipi', verbose_name='CST IPI')),
                ('cst_pis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.cstpis', verbose_name='CST PIS')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='empresas.loja', verbose_name='Loja')),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='empresas.matriz', verbose_name='Matriz')),
                ('ncm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regras_fiscais', to='fiscal.ncm', verbose_name='NCM')),
            ],
            options={
                'verbose_name': 'Regra fiscal',
                'verbose_name_plural': 'Regras fiscais',
                'db_table': 'fiscal_regra_fiscal',
                'ordering': ('prioridade', 'codigo_interno'),
                'indexes': [models.Index(fields=['ativo', 'prioridade'], name='fiscal_reg_ativo_prio_idx'), models.Index(fields=['regime_tributario', 'tipo_operacao', 'finalidade_operacao'], name='fiscal_reg_reg_tipo_fin_idx'), models.Index(fields=['uf_origem', 'uf_destino'], name='fiscal_reg_ufs_idx'), models.Index(fields=['matriz', 'loja', 'ativo'], name='fiscal_reg_escopo_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cst_icms__isnull', True), ('csosn__isnull', True), _connector='OR'), name='fiscal_reg_sem_cst_csosn_juntos')],
            },
        ),
    ]
