# Generated by Django 6.0.6 on 2026-08-06 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('fiscal', '0022_seed_regra_fiscal_homologacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscalMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_tributario', models.CharField(choices=[('todos', 'Todos'), ('normal', 'Regime normal'), ('simples', 'Simples Nacional'), ('mei', 'MEI')], max_length=12, verbose_name='Regime tributario')),
                ('uf_origem', models.CharField(max_length=2, verbose_name='UF de origem')),
                ('contribuinte_icms', models.BooleanField(verbose_name='Contribuinte do ICMS')),
                ('consumidor_final_padrao', models.BooleanField(verbose_name='Consumidor final padrao')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('matriz', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_fiscal', to='empresas.matriz', verbose_name='Matriz')),
            ],
            options={
                'verbose_name': 'Configuracao fiscal da matriz',
                'verbose_name_plural': 'Configuracoes fiscais das matrizes',
                'db_table': 'fiscal_configuracao_fiscal_matriz',
                'ordering': ('matriz__nome',),
            },
        ),
    ]
