# Generated by Django 6.0.6 on 2026-08-10 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('fiscal', '0023_configuracao_fiscal_matriz'),
        ('pdv', '0006_venda_uf_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modelo', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e')], max_length=2)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologacao'), ('producao', 'Producao')], max_length=20)),
                ('serie', models.PositiveSmallIntegerField()),
                ('numero', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chave_acesso', models.CharField(blank=True, default='', max_length=44)),
                ('codigo_numerico', models.CharField(blank=True, default='', max_length=8)),
                ('digito_verificador', models.CharField(blank=True, default='', max_length=1)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('preparado', 'Preparado'), ('pendente_transmissao', 'Pendente de transmissao'), ('transmitindo', 'Transmitindo'), ('autorizado', 'Autorizado'), ('rejeitado', 'Rejeitado'), ('denegado', 'Denegado'), ('contingencia', 'Contingencia'), ('cancelado', 'Cancelado'), ('erro', 'Erro')], db_index=True, default='rascunho', max_length=32)),
                ('tentativa_atual', models.PositiveIntegerField(default=0)),
                ('codigo_status', models.CharField(blank=True, default='', max_length=16)),
                ('motivo_status', models.TextField(blank=True, default='')),
                ('protocolo_autorizacao', models.CharField(blank=True, default='', max_length=64)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('xml_rascunho', models.TextField(blank=True, default='')),
                ('xml_assinado', models.TextField(blank=True, default='')),
                ('xml_autorizado', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('ultima_tentativa_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='empresas.matriz')),
                ('venda_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='pdv.vendafiscal')),
            ],
            options={
                'ordering': ('-criado_em', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('loja', 'modelo', 'ambiente', 'serie', 'numero'), name='uq_doc_fiscal_identidade_numerada'), models.UniqueConstraint(condition=models.Q(('chave_acesso', ''), _negated=True), fields=('chave_acesso',), name='uq_doc_fiscal_chave_preenchida'), models.CheckConstraint(condition=models.Q(('serie__gte', 1)), name='ck_doc_fiscal_serie_positiva'), models.CheckConstraint(condition=models.Q(('numero__isnull', True), ('numero__gte', 1), _connector='OR'), name='ck_doc_fiscal_numero_positivo')],
            },
        ),
        migrations.CreateModel(
            name='SequenciaDocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('55', 'NF-e'), ('65', 'NFC-e')], max_length=2)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologacao'), ('producao', 'Producao')], max_length=20)),
                ('serie', models.PositiveSmallIntegerField()),
                ('proximo_numero', models.PositiveBigIntegerField(default=1)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencias_documentos_fiscais', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequencias_documentos_fiscais', to='empresas.matriz')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('loja', 'modelo', 'ambiente', 'serie'), name='uq_sequencia_doc_fiscal_escopo'), models.CheckConstraint(condition=models.Q(('serie__gte', 1)), name='ck_seq_doc_fiscal_serie_positiva'), models.CheckConstraint(condition=models.Q(('proximo_numero__gte', 1)), name='ck_seq_doc_fiscal_numero_positivo')],
            },
        ),
    ]
