# Generated by Django 6.0.6 on 2026-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0026_configuracao_emissao_fiscal_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoemissaofiscalloja',
            name='certificado_a1_referencia',
            field=models.CharField(blank=True, default='', help_text='Referencia nao secreta para localizar o certificado A1 fora do repositorio. Nao armazene senha, chave privada ou conteudo do certificado neste campo.', max_length=255),
        ),
    ]
