# Generated by Django 6.0.6 on 2026-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0027_configuracaoemissaofiscalloja_certificado_a1_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='numero_recibo',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='xml_retorno',
            field=models.TextField(blank=True, default=''),
        ),
    ]
