# Generated by Django 6.0.6 on 2026-09-14 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('natureza', models.CharField(choices=[('PAGAR', 'Pagar'), ('RECEBER', 'Receber')], max_length=10)),
                ('origem_tipo', models.CharField(max_length=40)),
                ('origem_id', models.CharField(max_length=100)),
                ('chave_idempotencia', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcial'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=12)),
                ('data_emissao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_financeiros', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_financeiros', to='empresas.matriz')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('vencimento', models.DateField()),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberta'), ('PARCIAL', 'Parcial'), ('LIQUIDADO', 'Liquidada'), ('CANCELADO', 'Cancelada')], default='ABERTO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.titulofinanceiro')),
            ],
        ),
        migrations.CreateModel(
            name='BaixaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('BAIXA', 'Baixa'), ('ESTORNO', 'Estorno')], max_length=10)),
                ('chave_idempotencia', models.CharField(max_length=150)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.parcelafinanceira')),
            ],
            options={
                'indexes': [models.Index(fields=['parcela', 'data'], name='ix_fin_baixa_parc_data')],
                'constraints': [models.UniqueConstraint(fields=('parcela', 'chave_idempotencia'), name='uq_fin_baixa_parcela_idempotencia'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_fin_baixa_valor_positivo')],
            },
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['matriz', 'natureza', 'status'], name='ix_fin_tit_mat_nat_st'),
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['matriz', 'loja', 'status'], name='ix_fin_tit_mat_loja_st'),
        ),
        migrations.AddIndex(
            model_name='titulofinanceiro',
            index=models.Index(fields=['origem_tipo', 'origem_id'], name='ix_fin_tit_origem'),
        ),
        migrations.AddConstraint(
            model_name='titulofinanceiro',
            constraint=models.UniqueConstraint(fields=('matriz', 'chave_idempotencia'), name='uq_fin_titulo_matriz_idempotencia'),
        ),
        migrations.AddConstraint(
            model_name='titulofinanceiro',
            constraint=models.UniqueConstraint(fields=('matriz', 'natureza', 'origem_tipo', 'origem_id'), name='uq_fin_titulo_matriz_natureza_origem'),
        ),
        migrations.AddConstraint(
            model_name='titulofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='ck_fin_titulo_valor_positivo'),
        ),
        migrations.AddIndex(
            model_name='parcelafinanceira',
            index=models.Index(fields=['vencimento', 'status'], name='ix_fin_parc_venc_st'),
        ),
        migrations.AddIndex(
            model_name='parcelafinanceira',
            index=models.Index(fields=['titulo', 'status'], name='ix_fin_parc_tit_st'),
        ),
        migrations.AddConstraint(
            model_name='parcelafinanceira',
            constraint=models.UniqueConstraint(fields=('titulo', 'numero'), name='uq_fin_parcela_titulo_numero'),
        ),
        migrations.AddConstraint(
            model_name='parcelafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gt', 0)), name='ck_fin_parcela_numero_positivo'),
        ),
        migrations.AddConstraint(
            model_name='parcelafinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='ck_fin_parcela_valor_positivo'),
        ),
    ]
