# Generated by Django 6.0.6 on 2026-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulofinanceiro',
            name='origem_tipo',
            field=models.CharField(choices=[('COMPRA_RECEBIMENTO', 'Compra - recebimento'), ('VENDA_PAGAMENTO', 'Venda - pagamento'), ('MANUAL', 'Manual'), ('AJUSTE', 'Ajuste')], max_length=40),
        ),
    ]
