# Generated by Django 6.0.6 on 2026-09-14 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('financeiro', '0002_alter_titulofinanceiro_origem_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_bacen', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nome'], name='ix_fin_banco_nome')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo_bacen__isnull', False), models.Q(('codigo_bacen', ''), _negated=True)), fields=('codigo_bacen',), name='uq_fin_banco_codigo_bacen')],
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo_financeiros', to='empresas.matriz')),
            ],
            options={
                'indexes': [models.Index(fields=['matriz', 'ativo'], name='ix_fin_cc_mat_ativo')],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'codigo'), name='uq_fin_cc_matriz_codigo')],
            },
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('CONTA_CORRENTE', 'Conta corrente'), ('POUPANCA', 'Poupança'), ('CARTEIRA_DIGITAL', 'Carteira digital'), ('OUTRA', 'Outra')], max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('numero', models.CharField(blank=True, max_length=30)),
                ('digito', models.CharField(blank=True, max_length=10)),
                ('chave_pix', models.CharField(blank=True, max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='empresas.matriz')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_financeiras', to='financeiro.instituicaobancaria')),
            ],
            options={
                'indexes': [models.Index(fields=['matriz', 'ativo'], name='ix_fin_conta_mat_ativo'), models.Index(fields=['matriz', 'loja', 'ativo'], name='ix_fin_conta_mat_loja')],
            },
        ),
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('SINTETICA', 'Sintética'), ('ANALITICA', 'Analítica')], max_length=10)),
                ('natureza', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita'), ('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('OUTRO', 'Outro')], max_length=10)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('aceita_lancamento', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_contas_financeiros', to='empresas.matriz')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='financeiro.planoconta')),
            ],
            options={
                'indexes': [models.Index(fields=['matriz', 'ativo'], name='ix_fin_plano_mat_ativo'), models.Index(fields=['matriz', 'natureza'], name='ix_fin_plano_mat_nat')],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'codigo'), name='uq_fin_plano_matriz_codigo')],
            },
        ),
    ]
