# Generated by Django 6.0.6 on 2026-09-14 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_instituicaobancaria_centrocusto_contafinanceira_and_more'),
        ('pdv', '0007_congelamento_beneficio_fiscal_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixafinanceira',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_financeiras', to='financeiro.contafinanceira'),
        ),
        migrations.AddField(
            model_name='baixafinanceira',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_financeiras', to='pdv.formapagamento'),
        ),
        migrations.AddField(
            model_name='baixafinanceira',
            name='movimentacao_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_financeiras', to='pdv.movimentacaocaixa'),
        ),
        migrations.AddField(
            model_name='baixafinanceira',
            name='sessao_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_financeiras', to='pdv.sessaocaixa'),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_financeiros', to='financeiro.centrocusto'),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='entidade_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='plano_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulos_financeiros', to='financeiro.planoconta'),
        ),
    ]
