# Generated by Django 6.0.6 on 2026-09-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_baixafinanceira_conta_financeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulofinanceiro',
            name='data_competencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='titulofinanceiro',
            name='valor_juros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
