# Generated by Django 6.0.6 on 2026-09-21 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_titulofinanceiro_data_competencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixafinanceira',
            name='baixa_estornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='financeiro.baixafinanceira'),
        ),
    ]
