# Generated by Django 6.0.6 on 2026-07-21 13:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_email_normalizado_cliente_nome_normalizado_and_more'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_pdv', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_pdv', to='empresas.matriz')),
            ],
            options={
                'ordering': ['loja', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartao de credito'), ('cartao_debito', 'Cartao de debito'), ('crediario', 'Crediario'), ('vale', 'Vale'), ('cortesia', 'Cortesia'), ('outro', 'Outro')], db_index=True, default='outro', max_length=30)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('permite_parcelamento', models.BooleanField(default=False)),
                ('maximo_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('exige_cliente_identificado', models.BooleanField(default=False)),
                ('exige_autorizacao', models.BooleanField(default=False)),
                ('gera_contas_receber', models.BooleanField(default=False)),
                ('movimenta_caixa', models.BooleanField(default=True)),
                ('permite_troco', models.BooleanField(default=False)),
                ('somente_funcionario', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento_pdv', to='empresas.matriz')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=20)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_fechamento_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_fechamento_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('diferenca_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('aberta_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fechada_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('observacao_abertura', models.TextField(blank=True)),
                ('observacao_fechamento', models.TextField(blank=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='pdv.caixa')),
                ('operador_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_abertas', to=settings.AUTH_USER_MODEL)),
                ('operador_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_fechadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tipo_operacao', models.CharField(choices=[('venda', 'Venda'), ('orcamento', 'Orcamento'), ('espera', 'Venda em espera')], db_index=True, default='venda', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('orcamento', 'Orcamento'), ('espera', 'Em espera'), ('aberta', 'Aberta'), ('pagamento', 'Em pagamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], db_index=True, default='rascunho', max_length=20)),
                ('modalidade', models.CharField(choices=[('varejo', 'Varejo'), ('atacado', 'Atacado')], db_index=True, default='varejo', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('finalizada_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='empresas.matriz')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv_operadas', to=settings.AUTH_USER_MODEL)),
                ('sessao_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='pdv.sessaocaixa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv_vendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, max_length=120)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_pdv_autorizados', to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_venda', to='pdv.formapagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pdv.venda')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('abertura', 'Abertura'), ('venda', 'Venda'), ('suprimento', 'Suprimento'), ('sangria', 'Sangria'), ('estorno', 'Estorno'), ('fechamento', 'Fechamento')], db_index=True, max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('movimentacao_estornada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estorno_gerado', to='pdv.movimentacaocaixa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_caixa_pdv', to=settings.AUTH_USER_MODEL)),
                ('sessao_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='pdv.sessaocaixa')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_caixa', to='pdv.venda')),
            ],
            options={
                'ordering': ['criada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['matriz', 'status'], name='pdv_caixa_matriz__af9a28_idx'),
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['loja', 'status'], name='pdv_caixa_loja_id_368da7_idx'),
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['loja', 'nome'], name='pdv_caixa_loja_id_a3f357_idx'),
        ),
        migrations.AddConstraint(
            model_name='caixa',
            constraint=models.UniqueConstraint(fields=('loja', 'codigo'), name='uq_pdv_caixa_loja_codigo'),
        ),
        migrations.AddIndex(
            model_name='formapagamento',
            index=models.Index(fields=['matriz', 'ativa'], name='pdv_formapa_matriz__2bbb76_idx'),
        ),
        migrations.AddIndex(
            model_name='formapagamento',
            index=models.Index(fields=['matriz', 'tipo'], name='pdv_formapa_matriz__ee12c3_idx'),
        ),
        migrations.AddIndex(
            model_name='formapagamento',
            index=models.Index(fields=['matriz', 'nome'], name='pdv_formapa_matriz__ced250_idx'),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.UniqueConstraint(fields=('matriz', 'codigo'), name='uq_pdv_forma_pagamento_matriz_codigo'),
        ),
        migrations.AddConstraint(
            model_name='formapagamento',
            constraint=models.CheckConstraint(condition=models.Q(('maximo_parcelas__gte', 1)), name='ck_pdv_forma_pagamento_minimo_uma_parcela'),
        ),
        migrations.AddIndex(
            model_name='sessaocaixa',
            index=models.Index(fields=['caixa', 'status'], name='pdv_sessaoc_caixa_i_a3fb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocaixa',
            index=models.Index(fields=['operador_abertura', 'status'], name='pdv_sessaoc_operado_1fac85_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocaixa',
            index=models.Index(fields=['aberta_em'], name='pdv_sessaoc_aberta__930d34_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberta')), fields=('caixa',), name='uq_pdv_uma_sessao_aberta_por_caixa'),
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_abertura__gte', 0)), name='ck_pdv_sessao_valor_abertura_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['matriz', 'status'], name='pdv_venda_matriz__cc7e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['loja', 'status'], name='pdv_venda_loja_id_ad928f_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['sessao_caixa', 'status'], name='pdv_venda_sessao__a3eb45_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente', 'criada_em'], name='pdv_venda_cliente_f59183_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['operador', 'criada_em'], name='pdv_venda_operado_52356f_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['tipo_operacao', 'status'], name='pdv_venda_tipo_op_ba61b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('loja', 'numero'), name='uq_pdv_venda_loja_numero'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='ck_pdv_venda_subtotal_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='ck_pdv_venda_desconto_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('acrescimo__gte', 0)), name='ck_pdv_venda_acrescimo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venda',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_pdv_venda_total_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='pagamentovenda',
            index=models.Index(fields=['venda', 'forma_pagamento'], name='pdv_pagamen_venda_i_b8c19d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentovenda',
            index=models.Index(fields=['forma_pagamento', 'criado_em'], name='pdv_pagamen_forma_p_89be34_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamentovenda',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_pdv_pagamento_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagamentovenda',
            constraint=models.CheckConstraint(condition=models.Q(('parcelas__gte', 1)), name='ck_pdv_pagamento_minimo_uma_parcela'),
        ),
        migrations.AddConstraint(
            model_name='pagamentovenda',
            constraint=models.CheckConstraint(condition=models.Q(('troco__gte', 0)), name='ck_pdv_pagamento_troco_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocaixa',
            index=models.Index(fields=['sessao_caixa', 'tipo'], name='pdv_movimen_sessao__cd441a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocaixa',
            index=models.Index(fields=['sessao_caixa', 'criada_em'], name='pdv_movimen_sessao__3615a1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaocaixa',
            index=models.Index(fields=['venda', 'tipo'], name='pdv_movimen_venda_i_4feb2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaocaixa',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='ck_pdv_movimentacao_valor_positivo'),
        ),
    ]
