# Generated by Django 6.0.6 on 2026-07-21 15:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='acrescimo_geral',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_geral',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='venda',
            name='quantidade_itens',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sequencia', models.PositiveIntegerField()),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('acrescimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('cancelado', models.BooleanField(db_index=True, default=False)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda_cancelados', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda_pdv', to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='pdv.venda')),
            ],
            options={
                'ordering': ['venda', 'sequencia'],
                'indexes': [models.Index(fields=['venda', 'cancelado'], name='pdv_itemven_venda_i_eed773_idx'), models.Index(fields=['produto', 'criado_em'], name='pdv_itemven_produto_2b60ed_idx'), models.Index(fields=['venda', 'sequencia'], name='pdv_itemven_venda_i_6097c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('venda', 'sequencia'), name='uq_pdv_item_venda_sequencia'), models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='ck_pdv_item_venda_quantidade_positiva'), models.CheckConstraint(condition=models.Q(('preco_unitario__gte', 0)), name='ck_pdv_item_venda_preco_nao_negativo'), models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='ck_pdv_item_venda_desconto_nao_negativo'), models.CheckConstraint(condition=models.Q(('acrescimo__gte', 0)), name='ck_pdv_item_venda_acrescimo_nao_negativo'), models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_pdv_item_venda_total_nao_negativo')],
            },
        ),
    ]
