# Generated by Django 6.0.6 on 2026-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_venda_acrescimo_geral_venda_desconto_geral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='tipo_emissao',
            field=models.CharField(choices=[('nao_fiscal', 'Nao fiscal'), ('fiscal', 'Fiscal')], db_index=True, default='nao_fiscal', max_length=20),
        ),
    ]
