# Generated by Django 6.0.6 on 2026-08-01 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_venda_tipo_emissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberta')), fields=('operador_abertura',), name='uq_pdv_uma_sessao_aberta_por_operador'),
        ),
    ]
