# Generated by Django 6.0.6 on 2026-08-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_itemvendafiscal_vendafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='uf_destino',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF de destino'),
        ),
    ]
