# Generated by Django 6.0.6 on 2026-09-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_congelamento_beneficio_fiscal_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='gera_cashback',
            field=models.BooleanField(default=True),
        ),
    ]
