# Generated by Django 6.0.6 on 2026-06-23 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaAniversarioEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=150)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas_aniversario', to='clientes.cliente')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_aniversario', to='empresas.matriz')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['matriz', 'canal'], name='campanhas_c_matriz__090e2a_idx'), models.Index(fields=['matriz', 'status'], name='campanhas_c_matriz__510f80_idx'), models.Index(fields=['matriz', 'criado_em'], name='campanhas_c_matriz__06add8_idx'), models.Index(fields=['cliente', 'canal'], name='campanhas_c_cliente_ae785f_idx')],
            },
        ),
    ]
