# Generated by Django 6.0.6 on 2026-06-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhaaniversarioenvio',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=20),
        ),
    ]
