# Generated by Django 6.0.6 on 2026-06-24 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_alter_campanhaaniversarioenvio_status'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCampanhaAniversario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('canal_padrao', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=20)),
                ('assunto_padrao', models.CharField(default='Feliz aniversário! Temos um presente especial para você', max_length=150)),
                ('mensagem_padrao', models.TextField(default='Olá, {nome}! A equipe preparou uma condição especial para comemorar seu aniversário. Entre em contato e aproveite!')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_campanha_aniversario', to='empresas.matriz')),
            ],
            options={
                'verbose_name': 'Configuração de Campanha de Aniversário',
                'verbose_name_plural': 'Configurações de Campanhas de Aniversário',
            },
        ),
    ]
