# Generated by Django 6.0.6 on 2026-06-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_configuracaocampanhaaniversario'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('aniversario', 'Aniversário'), ('cashback_expirando', 'Cashback Expirando'), ('boas_vindas', 'Boas-vindas'), ('personalizada', 'Personalizada')], db_index=True, default='personalizada', max_length=30)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], db_index=True, default='whatsapp', max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=150)),
                ('mensagem', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_campanhas', to='empresas.matriz')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['matriz', 'tipo'], name='campanhas_t_matriz__6cbce0_idx'), models.Index(fields=['matriz', 'canal'], name='campanhas_t_matriz__ca881f_idx'), models.Index(fields=['matriz', 'ativo'], name='campanhas_t_matriz__575387_idx')],
            },
        ),
    ]
