# Generated by Django 6.0.6 on 2026-06-26 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_templatecampanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhaaniversarioenvio',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_aniversario', to='campanhas.templatecampanha'),
        ),
    ]
