PERMISSAO_FISCAL_VISUALIZAR = "fiscal.visualizar"
PERMISSAO_FISCAL_CONFIGURAR = "fiscal.configurar"
PERMISSAO_FISCAL_GERENCIAR_CADASTROS = "fiscal.gerenciar_cadastros"

PERMISSOES_FISCAL = {
    PERMISSAO_FISCAL_VISUALIZAR,
    PERMISSAO_FISCAL_CONFIGURAR,
    PERMISSAO_FISCAL_GERENCIAR_CADASTROS,
}
