# Generated by Django 6.0.6 on 2026-07-01 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_email_normalizado_cliente_nome_normalizado_and_more'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('valor_fixo', 'Valor fixo'), ('percentual', 'Percentual')], db_index=True, max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('campanha', 'Campanha'), ('aniversario', 'Aniversário'), ('importacao', 'Importação'), ('indicacao', 'Indicação'), ('fidelidade', 'Fidelidade')], db_index=True, default='manual', max_length=30)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], db_index=True, default='ativo', max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_inicio', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(db_index=True)),
                ('uso_unico_por_cliente', models.BooleanField(default=True)),
                ('limite_utilizacao', models.PositiveIntegerField(default=1)),
                ('total_utilizado', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='clientes.cliente')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='empresas.matriz')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UsoVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_vouchers', to='clientes.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_vouchers', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_vouchers', to='empresas.matriz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_vouchers', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_permitidos', to='empresas.loja')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas_permitidas', to='vouchers.voucher')),
            ],
            options={
                'ordering': ['loja__nome'],
            },
        ),
        migrations.DeleteModel(
            name='VoucherIndicacao',
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['matriz', 'codigo'], name='vouchers_vo_matriz__f958f4_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['matriz', 'status'], name='vouchers_vo_matriz__35de02_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['matriz', 'origem'], name='vouchers_vo_matriz__5b2f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['matriz', 'cliente'], name='vouchers_vo_matriz__53184a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['matriz', 'data_inicio'], name='vouchers_vo_matriz__f0ea5a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['matriz', 'data_fim'], name='vouchers_vo_matriz__4088e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('percentual__isnull', True), ('tipo', 'valor_fixo'), ('valor__isnull', False)), models.Q(('percentual__isnull', False), ('tipo', 'percentual'), ('valor__isnull', True)), _connector='OR'), name='voucher_tipo_valor_ou_percentual'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('limite_utilizacao__gt', 0)), name='voucher_limite_utilizacao_maior_que_zero'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('total_utilizado__gte', 0)), name='voucher_total_utilizado_nao_negativo'),
        ),
        migrations.AddIndex(
            model_name='usovoucher',
            index=models.Index(fields=['matriz', 'cliente'], name='vouchers_us_matriz__011d10_idx'),
        ),
        migrations.AddIndex(
            model_name='usovoucher',
            index=models.Index(fields=['matriz', 'voucher'], name='vouchers_us_matriz__c4aa2b_idx'),
        ),
        migrations.AddIndex(
            model_name='usovoucher',
            index=models.Index(fields=['matriz', 'loja'], name='vouchers_us_matriz__26407f_idx'),
        ),
        migrations.AddIndex(
            model_name='usovoucher',
            index=models.Index(fields=['voucher', 'cliente'], name='vouchers_us_voucher_6ef031_idx'),
        ),
        migrations.AddIndex(
            model_name='usovoucher',
            index=models.Index(fields=['criado_em'], name='vouchers_us_criado__8f680c_idx'),
        ),
        migrations.AddConstraint(
            model_name='usovoucher',
            constraint=models.CheckConstraint(condition=models.Q(('valor_compra__gt', 0)), name='uso_voucher_valor_compra_maior_que_zero'),
        ),
        migrations.AddConstraint(
            model_name='usovoucher',
            constraint=models.CheckConstraint(condition=models.Q(('valor_desconto__gt', 0)), name='uso_voucher_valor_desconto_maior_que_zero'),
        ),
        migrations.AddIndex(
            model_name='voucherloja',
            index=models.Index(fields=['voucher', 'loja'], name='vouchers_vo_voucher_3a504b_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherloja',
            index=models.Index(fields=['loja'], name='vouchers_vo_loja_id_6a9d6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucherloja',
            constraint=models.UniqueConstraint(fields=('voucher', 'loja'), name='uq_voucher_loja'),
        ),
    ]
