# Generated by Django 6.0.6 on 2026-07-04 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
        ('clientes', '0003_cliente_email_normalizado_cliente_nome_normalizado_and_more'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('vouchers', '0002_voucher_usovoucher_voucherloja_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usovoucher',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_utilizados', to='cashback.lancamentocashback'),
        ),
        migrations.AddIndex(
            model_name='usovoucher',
            index=models.Index(fields=['voucher', 'criado_em'], name='vouchers_us_voucher_b7bd55_idx'),
        ),
    ]
