# Generated by Django 6.0.6 on 2026-06-22 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(db_index=True, max_length=14)),
                ('telefone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('aceita_email', models.BooleanField(default=True)),
                ('aceita_sms', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_cadastrados', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.matriz')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['matriz', 'cpf'], name='clientes_cl_matriz__326542_idx'), models.Index(fields=['matriz', 'nome'], name='clientes_cl_matriz__68b8d3_idx'), models.Index(fields=['matriz', 'telefone'], name='clientes_cl_matriz__979fce_idx'), models.Index(fields=['matriz', 'email'], name='clientes_cl_matriz__3178df_idx'), models.Index(fields=['matriz', 'data_nascimento'], name='clientes_cl_matriz__ecf114_idx'), models.Index(fields=['matriz', 'ativo'], name='clientes_cl_matriz__85cdc8_idx'), models.Index(fields=['loja_cadastro', 'criado_em'], name='clientes_cl_loja_ca_8cf20a_idx')],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'cpf'), name='unique_cliente_por_matriz_cpf')],
            },
        ),
    ]
