# Generated by Django 6.0.6 on 2026-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=11),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['matriz', 'cpf_normalizado'], name='clientes_cl_matriz__e6c324_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['matriz', 'telefone_normalizado'], name='clientes_cl_matriz__651281_idx'),
        ),
    ]
