# Generated by Django 6.0.6 on 2026-06-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cpf_normalizado_cliente_telefone_normalizado_and_more'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_normalizado',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['matriz', 'nome_normalizado'], name='clientes_cl_matriz__0517e2_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['matriz', 'email_normalizado'], name='clientes_cl_matriz__6bd266_idx'),
        ),
    ]
