# Generated by Django 6.0.6 on 2026-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_email_normalizado_cliente_nome_normalizado_and_more'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cliente',
            name='unique_cliente_por_matriz_cpf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_responsavel',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_pessoa', 'PF'), models.Q(('cpf_normalizado', ''), _negated=True)), fields=('matriz', 'cpf_normalizado'), name='unique_cliente_pf_por_matriz_cpf_norm'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_pessoa', 'PJ'), models.Q(('cnpj_normalizado', ''), _negated=True)), fields=('matriz', 'cnpj_normalizado'), name='unique_cliente_pj_por_matriz_cnpj_norm'),
        ),
    ]
