# Generated by Django 6.0.6 on 2026-07-17 21:26

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(db_index=True, max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, db_index=True, max_length=180)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contato_principal', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], db_index=True, default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='empresas.matriz')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social', 'id'],
                'indexes': [models.Index(fields=['matriz', 'status'], name='compras_for_matriz_status_idx'), models.Index(fields=['matriz', 'razao_social'], name='compras_for_matriz_razao_idx'), models.Index(fields=['matriz', 'cnpj'], name='compras_for_matriz_cnpj_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('matriz', 'cnpj'), name='unique_fornecedor_matriz_cnpj'), models.UniqueConstraint(django.db.models.functions.text.Lower('razao_social'), models.F('matriz'), name='unique_fornecedor_matriz_razao_ci')],
            },
        ),
    ]
