# Generated by Django 6.0.6 on 2026-07-17 21:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.PositiveBigIntegerField(editable=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao fornecedor'), ('parcial', 'Recebido parcialmente'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20)),
                ('data_emissao', models.DateField(db_index=True)),
                ('previsao_entrega', models.DateField(blank=True, db_index=True, null=True)),
                ('condicao_pagamento', models.CharField(blank=True, max_length=120)),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='compras.fornecedor')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='empresas.matriz')),
            ],
            options={
                'verbose_name': 'Pedido de compra',
                'verbose_name_plural': 'Pedidos de compra',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='produtos.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra')),
            ],
            options={
                'verbose_name': 'Item do pedido de compra',
                'verbose_name_plural': 'Itens do pedido de compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['matriz', 'status', 'data_emissao'], name='compras_ped_mat_status_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['matriz', 'fornecedor'], name='compras_ped_matriz_fornec_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.UniqueConstraint(fields=('matriz', 'numero'), name='unique_pedido_compra_matriz_numero'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('frete__gte', 0)), name='pedido_compra_frete_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('desconto__gte', 0)), name='pedido_compra_desconto_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.UniqueConstraint(fields=('pedido', 'produto'), name='unique_item_pedido_compra_produto'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_pedido_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='item_pedido_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_recebida__gte', 0)), name='item_pedido_recebido_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itempedidocompra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_recebida__lte', models.F('quantidade'))), name='item_pedido_recebido_ate_quantidade'),
        ),
    ]
