# Generated by Django 6.0.6 on 2026-07-17 22:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_pedidocompra_itempedidocompra_and_more'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('estoque', '0003_reserva_estoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chave_idempotencia', models.CharField(max_length=100)),
                ('documento_referencia', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_compra', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_compra', to='empresas.matriz')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='compras.pedidocompra')),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos_compra_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recebido_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecebimentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='compras.itempedidocompra')),
                ('movimentacao_estoque', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='item_recebimento_compra', to='estoque.movimentacaoestoque')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.recebimentocompra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='recebimentocompra',
            index=models.Index(fields=['matriz', 'pedido'], name='rec_compra_mat_ped_idx'),
        ),
        migrations.AddIndex(
            model_name='recebimentocompra',
            index=models.Index(fields=['matriz', 'loja', 'recebido_em'], name='rec_compra_mat_loja_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='recebimentocompra',
            constraint=models.UniqueConstraint(fields=('matriz', 'chave_idempotencia'), name='uq_rec_compra_mat_idemp'),
        ),
        migrations.AddConstraint(
            model_name='itemrecebimentocompra',
            constraint=models.UniqueConstraint(fields=('recebimento', 'item_pedido'), name='uq_item_rec_compra_pedido'),
        ),
        migrations.AddConstraint(
            model_name='itemrecebimentocompra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_rec_compra_qtd_pos'),
        ),
    ]
