# Generated by Django 6.0.6 on 2026-07-17 22:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_recebimentocompra_itemrecebimentocompra_and_more'),
        ('empresas', '0005_remove_loja_empresas_lo_matriz__cad783_idx_and_more'),
        ('estoque', '0003_reserva_estoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecebimentocompra',
            name='quantidade_devolvida',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.CreateModel(
            name='DevolucaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chave_idempotencia', models.CharField(max_length=100)),
                ('documento_referencia', models.CharField(blank=True, max_length=80)),
                ('motivo', models.TextField()),
                ('devolvido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('devolvido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_compra_realizadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_compra', to='empresas.loja')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_compra', to='empresas.matriz')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='compras.recebimentocompra')),
            ],
            options={
                'ordering': ['-devolvido_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.devolucaocompra')),
                ('item_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='compras.itemrecebimentocompra')),
                ('movimentacao_estoque', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='item_devolucao_compra', to='estoque.movimentacaoestoque')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='devolucaocompra',
            index=models.Index(fields=['matriz', 'recebimento'], name='dev_compra_mat_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucaocompra',
            index=models.Index(fields=['matriz', 'loja', 'devolvido_em'], name='dev_compra_mat_loja_dt_idx'),
        ),
        migrations.AddConstraint(
            model_name='devolucaocompra',
            constraint=models.UniqueConstraint(fields=('matriz', 'chave_idempotencia'), name='uq_dev_compra_mat_idemp'),
        ),
        migrations.AddConstraint(
            model_name='itemdevolucaocompra',
            constraint=models.UniqueConstraint(fields=('devolucao', 'item_recebimento'), name='uq_item_dev_compra_rec'),
        ),
        migrations.AddConstraint(
            model_name='itemdevolucaocompra',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_dev_compra_qtd_pos'),
        ),
    ]
