# Generated by Django 6.0.6 on 2026-06-22 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=18, null=True, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='empresas_ma_nome_1271fc_idx'), models.Index(fields=['ativa'], name='empresas_ma_ativa_e3e38a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lojas', to='empresas.matriz')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['matriz', 'nome'], name='empresas_lo_matriz__aceed8_idx'), models.Index(fields=['matriz', 'cnpj'], name='empresas_lo_matriz__953e09_idx'), models.Index(fields=['matriz', 'ativa'], name='empresas_lo_matriz__cad783_idx')],
                'constraints': [models.UniqueConstraint(fields=('matriz', 'cnpj'), name='unique_loja_por_matriz_cnpj')],
            },
        ),
    ]
