# Generated by Django 6.0.6 on 2026-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matriz',
            name='empresas_ma_ativa_e3e38a_idx',
        ),
        migrations.AddField(
            model_name='matriz',
            name='status',
            field=models.CharField(choices=[('implantacao', 'Em implantação'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('bloqueada', 'Bloqueada')], db_index=True, default='ativa', max_length=20),
        ),
        migrations.AddIndex(
            model_name='matriz',
            index=models.Index(fields=['status'], name='empresas_ma_status_e0252d_idx'),
        ),
        migrations.AddIndex(
            model_name='matriz',
            index=models.Index(fields=['ativa', 'status'], name='empresas_ma_ativa_9e930d_idx'),
        ),
    ]
