# Generated by Django 6.0.6 on 2026-06-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_matriz_empresas_ma_ativa_e3e38a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matriz',
            name='empresas_ma_ativa_9e930d_idx',
        ),
        migrations.RemoveField(
            model_name='matriz',
            name='ativa',
        ),
    ]
