# Generated by Django 6.0.6 on 2026-06-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_matriz_empresas_ma_ativa_9e930d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriz',
            name='status',
            field=models.CharField(choices=[('implantacao', 'Em implantação'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('bloqueada', 'Bloqueada'), ('encerrada', 'Encerrada')], db_index=True, default='ativa', max_length=20),
        ),
    ]
