# Generated by Django 6.0.6 on 2026-06-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_matriz_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loja',
            name='empresas_lo_matriz__cad783_idx',
        ),
        migrations.AddField(
            model_name='loja',
            name='status',
            field=models.CharField(choices=[('implantacao', 'Em implantação'), ('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('bloqueada', 'Bloqueada'), ('encerrada', 'Encerrada')], db_index=True, default='implantacao', max_length=20),
        ),
        migrations.AddIndex(
            model_name='loja',
            index=models.Index(fields=['matriz', 'status'], name='empresas_lo_matriz__65aba5_idx'),
        ),
        migrations.RemoveField(
            model_name='loja',
            name='ativa',
        ),
    ]
